{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ad_config_search.waymo_utils import frames_from_path, simplify_ids, simplify_fnames, get_frame_dict\n",
    "from pathlib import Path\n",
    "import pickle\n",
    "import ray"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "metadata": {},
   "outputs": [],
   "source": [
    "ray.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-11-25 12:05:18,760\tINFO resource_spec.py:231 -- Starting Ray with 52.93 GiB memory available for workers and up to 26.49 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).\n",
      "2020-11-25 12:05:19,166\tINFO services.py:1193 -- View the Ray dashboard at \u001b[1m\u001b[32mlocalhost:8265\u001b[39m\u001b[22m\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'node_ip_address': '169.229.48.111',\n",
       " 'raylet_ip_address': '169.229.48.111',\n",
       " 'redis_address': '169.229.48.111:6379',\n",
       " 'object_store_address': '/tmp/ray/session_2020-11-25_12-05-18_756815_29435/sockets/plasma_store',\n",
       " 'raylet_socket_name': '/tmp/ray/session_2020-11-25_12-05-18_756815_29435/sockets/raylet',\n",
       " 'webui_url': 'localhost:8265',\n",
       " 'session_dir': '/tmp/ray/session_2020-11-25_12-05-18_756815_29435'}"
      ]
     },
     "execution_count": 109,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ray.init(redis_password=\"asdfakljdsflkdjfldkfjldkfj23383u48hjfhfhfhf\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_path = Path(\"/data/ges/waymo/training_0005/\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {},
   "outputs": [],
   "source": [
    "name_map = simplify_fnames(data_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Rename from hash to a readable name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "metadata": {},
   "outputs": [],
   "source": [
    "for path in data_path.iterdir():\n",
    "    ext = path.name.split(\".\")[-1]\n",
    "    if ext != \"tfrecord\":\n",
    "        continue\n",
    "    new_name = path.parent/(name_map[path.stem]+\".tfrecord\")\n",
    "    path.rename(new_name)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Generate pl files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 111,
   "metadata": {},
   "outputs": [],
   "source": [
    "@ray.remote\n",
    "def prepare_pl(data_path):\n",
    "    data_path = Path(data_path)\n",
    "    frames = frames_from_path(data_path)\n",
    "    id_map = simplify_ids(frames)\n",
    "    dicts = [get_frame_dict(f, id_map, rbg=False)[\"FRONT\"] for f in frames]\n",
    "    for d in dicts:\n",
    "        d[\"center_camera_feed\"] = d[\"img\"]\n",
    "        del d['img']\n",
    "    with open(data_path.parent/(data_path.stem+\".pl\"), 'wb') as f:\n",
    "        pickle.dump(dicts, f)\n",
    "    return 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 112,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:23.438857: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:23.439079: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:23.439091: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:23.443248: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:23.443319: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:23.443325: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:23.441053: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:23.441122: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:23.441129: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:23.439593: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:23.439726: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:23.439743: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:23.439054: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:23.439142: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:23.439153: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:23.444209: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:23.444328: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:23.444342: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:23.438813: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:23.439078: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:23.439088: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:23.439422: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:23.439562: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:23.439581: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:23.438859: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:23.439079: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:23.439091: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:23.438824: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:23.439084: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:23.439101: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:23.438828: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:23.439078: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:23.439087: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:23.438833: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:23.439073: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:23.439080: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:23.439062: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:23.439143: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:23.439153: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:23.438824: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:23.439070: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:23.439081: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:23.455360: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:23.455476: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:23.455489: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:23.461545: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:23.461619: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:23.461625: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:23.467114: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:23.467196: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:23.467203: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:23.514246: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:23.514303: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:23.514310: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:23.483603: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:23.483681: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:23.483688: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:23.475813: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:23.475881: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:23.475888: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:23.511919: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:23.512025: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:23.512038: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:23.513976: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:23.514043: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:23.514049: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:23.517458: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:23.517535: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:23.517542: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:23.554675: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:23.554776: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:23.554788: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:23.527049: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:23.527176: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:23.527189: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.520791: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.539570: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.539605: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.539612: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.539807: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.539834: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.539841: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.540622: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.540416: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.529130: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.540615: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.540658: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.540668: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.540812: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.540841: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.540849: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.541327: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.538600: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542189: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542222: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542227: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542308: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542334: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542338: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.542652: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.520396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.539457: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.539505: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.539513: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.539808: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.539834: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.539841: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.540618: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.520386: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.539465: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.539506: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.539513: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.539808: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.539835: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.539841: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.540627: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.520391: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.539966: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.540021: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.540030: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.540154: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.540187: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.540196: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.540674: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.520395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.539713: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.539747: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.539754: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.539874: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.539895: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.539900: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.540623: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.545313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543475: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543503: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543508: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543603: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543621: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543627: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.543914: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548095: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548124: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548130: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548234: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548253: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548258: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.548545: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.549656: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553298: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553339: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553345: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553447: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553468: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553473: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.553813: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.555455: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.556409: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.556564: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.554924: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.557353: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55aa4e876370 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11658)\u001b[0m 2020-11-25 12:05:24.557383: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.555178: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.557495: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56396d259cf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11678)\u001b[0m 2020-11-25 12:05:24.557521: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.554929: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.557356: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5640287944d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11670)\u001b[0m 2020-11-25 12:05:24.557389: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.557975: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.557665: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b6ee471560 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11738)\u001b[0m 2020-11-25 12:05:24.557694: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.558339: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56314e3920e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11666)\u001b[0m 2020-11-25 12:05:24.558362: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.560034: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.559514: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.559550: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.559556: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.559662: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.559682: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.559687: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.560034: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.560214: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.559687: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561a94c9dbe0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11643)\u001b[0m 2020-11-25 12:05:24.559709: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.560840: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.560243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.562641: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.562726: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561031f0ee30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11649)\u001b[0m 2020-11-25 12:05:24.562752: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.562488: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.607652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.613664: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.613735: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.613746: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.613948: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.613989: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.613998: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.614492: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.571530: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.571573: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.571584: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.571713: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.571745: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.571755: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.572231: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.584623: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.586665: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56406cd1a5f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11645)\u001b[0m 2020-11-25 12:05:24.586693: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.572070: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.575727: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.575767: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.575777: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.575893: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.575923: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.575930: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.576387: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.595645: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.597807: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5586cd0350c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11696)\u001b[0m 2020-11-25 12:05:24.597850: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.606440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.612892: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.612934: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.612944: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.613078: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.613109: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.613118: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.613518: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.614805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.570910: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.573096: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d885f590c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11642)\u001b[0m 2020-11-25 12:05:24.573121: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.605579: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.609969: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.610003: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.610009: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.610132: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.610151: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.610156: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.610606: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.573966: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.576501: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55fd97a2aef0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11668)\u001b[0m 2020-11-25 12:05:24.576537: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.573928: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.576277: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e7c4880e90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11656)\u001b[0m 2020-11-25 12:05:24.576302: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.566153: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.567881: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e951efe8e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11661)\u001b[0m 2020-11-25 12:05:24.567906: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.569714: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.569759: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.569768: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.569939: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.569969: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.569977: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.570436: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.583913: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.586391: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5588a4f24fd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11669)\u001b[0m 2020-11-25 12:05:24.586424: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.570882: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.570925: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.570936: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.571056: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.571090: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.571098: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.571537: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.584240: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.586463: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56478654ab80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11655)\u001b[0m 2020-11-25 12:05:24.586501: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.571373: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.571424: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.571435: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.571593: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.571627: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.571635: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.572177: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.583607: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.585557: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56525c405210 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11724)\u001b[0m 2020-11-25 12:05:24.585587: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.568603: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.568647: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.568655: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.568763: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.568787: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.568793: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.569126: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.582715: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.584874: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560049ba9ec0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11654)\u001b[0m 2020-11-25 12:05:24.584909: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.620574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.618515: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.618558: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.618565: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.618692: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.618715: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.618720: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.619100: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.621755: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.623962: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.624021: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.624033: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.624160: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.624196: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.624204: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.624769: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.641442: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.644175: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a5410c54f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11664)\u001b[0m 2020-11-25 12:05:24.644236: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.627519: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.629442: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ed11637480 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11653)\u001b[0m 2020-11-25 12:05:24.629474: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.628177: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.630526: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e86f630bf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11659)\u001b[0m 2020-11-25 12:05:24.630559: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.629728: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.631987: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562c3e57bf60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11651)\u001b[0m 2020-11-25 12:05:24.632019: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.627573: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d38a1c3940 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11646)\u001b[0m 2020-11-25 12:05:24.627625: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.661240: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.665330: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.665398: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.665405: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.665576: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.665601: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.665606: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.666121: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.677292: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.679598: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5654c2bbd530 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11641)\u001b[0m 2020-11-25 12:05:24.679644: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.649554: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.655412: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.655486: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.655496: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.655726: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.655768: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.655777: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.656579: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.672465: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.674828: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559a6f2c4790 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11657)\u001b[0m 2020-11-25 12:05:24.674871: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.681620: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.685317: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.685380: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.685387: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: erdos3\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.685555: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.685583: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.685589: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.686080: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.698920: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.700917: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5638e02d4400 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
      "\u001b[2m\u001b[36m(pid=11672)\u001b[0m 2020-11-25 12:05:24.700967: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
      "2020-11-25 12:06:33,302\tWARNING worker.py:1134 -- A worker died or was killed while executing task 7575bebcb06c25a7ffffffff0100.\n",
      "\u001b[2m\u001b[33m(pid=raylet)\u001b[0m E1125 12:06:33.297417 11593 11593 node_manager.cc:3671] Failed to send get core worker stats request: IOError: 14: Connection reset by peer\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "([ObjectRef(7575bebcb06c25a7ffffffff010000c001000000)],\n",
       " [ObjectRef(f21dc89fadaee218ffffffff010000c001000000),\n",
       "  ObjectRef(46553e94847e2b37ffffffff010000c001000000),\n",
       "  ObjectRef(6087e1b1ed98a18affffffff010000c001000000),\n",
       "  ObjectRef(01ad35894212eb6affffffff010000c001000000),\n",
       "  ObjectRef(c2f66569a02c666cffffffff010000c001000000),\n",
       "  ObjectRef(d7bcc9b4e43bda85ffffffff010000c001000000),\n",
       "  ObjectRef(6818461f4a23329fffffffff010000c001000000),\n",
       "  ObjectRef(06d17ebff4fc93e3ffffffff010000c001000000),\n",
       "  ObjectRef(52560c3652f3285fffffffff010000c001000000),\n",
       "  ObjectRef(443e4949d2779ff5ffffffff010000c001000000),\n",
       "  ObjectRef(b2356f7380ee1cb7ffffffff010000c001000000),\n",
       "  ObjectRef(5503b58b2d0cce65ffffffff010000c001000000),\n",
       "  ObjectRef(623f7cd8e611e75dffffffff010000c001000000),\n",
       "  ObjectRef(efa8bd43e6b37b97ffffffff010000c001000000),\n",
       "  ObjectRef(2ba66db8c83e52cfffffffff010000c001000000),\n",
       "  ObjectRef(4ff517a2730e7822ffffffff010000c001000000),\n",
       "  ObjectRef(98840b760a174a58ffffffff010000c001000000),\n",
       "  ObjectRef(e0332cb2bfd80556ffffffff010000c001000000),\n",
       "  ObjectRef(69e74be9000453d8ffffffff010000c001000000),\n",
       "  ObjectRef(6ff522865ba055ddffffffff010000c001000000),\n",
       "  ObjectRef(3036c2d52d9971e8ffffffff010000c001000000),\n",
       "  ObjectRef(4d632d12e78e0cdaffffffff010000c001000000),\n",
       "  ObjectRef(5f267175bff4e3fcffffffff010000c001000000),\n",
       "  ObjectRef(2814bb78e88f8095ffffffff010000c001000000)])"
      ]
     },
     "execution_count": 112,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-11-25 12:06:44,326\tERROR worker.py:1074 -- Possible unhandled error from worker: \u001b[36mray::__main__.prepare_pl()\u001b[39m (pid=11687, ip=169.229.48.111)\n",
      "  File \"python/ray/_raylet.pyx\", line 440, in ray._raylet.execute_task\n",
      "  File \"/home/eyal/miniconda3/envs/waymo_env/lib/python3.7/site-packages/ray/memory_monitor.py\", line 128, in raise_if_low_memory\n",
      "    self.error_threshold))\n",
      "ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node erdos3 is used (92.43 / 94.06 GB). The top 10 memory consumers are:\n",
      "\n",
      "PID\tMEM\tCOMMAND\n",
      "11655\t3.65GiB\tray::__main__.prepare_pl()\n",
      "11668\t3.65GiB\tray::__main__.prepare_pl()\n",
      "11659\t3.55GiB\tray::__main__.prepare_pl()\n",
      "11738\t3.51GiB\tray::__main__.prepare_pl()\n",
      "11661\t3.45GiB\tray::__main__.prepare_pl()\n",
      "11651\t3.43GiB\tray::__main__.prepare_pl()\n",
      "11643\t3.41GiB\tray::__main__.prepare_pl()\n",
      "11656\t3.38GiB\tray::__main__.prepare_pl()\n",
      "11664\t3.32GiB\tray::__main__.prepare_pl()\n",
      "11678\t3.32GiB\tray::__main__.prepare_pl()\n",
      "\n",
      "In addition, up to 0.01 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.\n",
      "---\n",
      "--- Tip: Use the `ray memory` command to list active objects in the cluster.\n",
      "---\n",
      "2020-11-25 12:06:47,239\tWARNING worker.py:1134 -- A worker died or was killed while executing task 69e74be9000453d8ffffffff0100.\n",
      "\u001b[2m\u001b[33m(pid=raylet)\u001b[0m E1125 12:06:47.228758 11593 11593 node_manager.cc:3671] Failed to send get core worker stats request: IOError: 14: Connection reset by peer\n"
     ]
    }
   ],
   "source": [
    "callbacks = []\n",
    "for path in data_path.iterdir():\n",
    "    ext = path.name.split(\".\")[-1]\n",
    "    if ext != \"tfrecord\":\n",
    "        continue\n",
    "    callbacks.append(prepare_pl.remote(path))\n",
    "ray.wait(callbacks)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (waymo_env)",
   "language": "python",
   "name": "waymo_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
